name: Create container, push and deploy

on:
  push:
    branches: [ development ] #for testing
  release:
    types: [published]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip deploy')" # will not run if the commit contains that phrase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Docker Meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ghcr.io/towech-financeApp/WebClient
        tag-sha: true
        tag-edge: false
        tag-latest: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        target: 'prod'
        file: ./Dockerfile
        build-args: |
          REACT_APP_WEBAPI=https://financeapi.towechlabs.com
        
  # build:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true

  #     - name: docker build 
  #       run: |
  #         docker build . --target prod --tag webclient:latest --build-arg REACT_APP_WEBAPI=financeapi.towechlabs.com

  # deploy:
  #   needs: build
  #   runs-on: self-hosted
  #   steps:
  #     - name: deployment
  #       run: |
  #         docker rm -f webClient 2> /dev/null || true
  #         docker run -d \
  #         --restart unless-stopped \
  #         --name webClient \
  #         --network towech-finance-network \
  #         -p 3000:80 \
  #         -e REACT_APP_WEBAPI=financeapi.towechlabs.com \
  #         webclient:latest
  #         docker image prune -f
