name: Create container, push and deploy

on:
  #for testing
  # push:
  #   branches: [development]

  release:
    types: [published]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip deploy')" # will not run if the commit contains that phrase
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Docker Meta
      id: docker_meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/towech-financeApp/WebClient

    - name: Setup QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1.0.1
      with:
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1.0.4

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
        target: 'prod'
        file: ./Dockerfile
        build-args: |
          REACT_APP_WEBAPI=${{ secrets.API_URL }}

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: deployment
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_KEY }}
  #         script: |
  #           docker rm -f webClient 2> /dev/null || true
  #           docker image rm ghcr.io/towech-financeapp/webclient 2> /dev/null || true
  #           docker pull ghcr.io/towech-financeapp/webclient:latest
  #           docker run -d \
  #           --restart unless-stopped \
  #           --name webClient \
  #           --network towech-finance-network \
  #           -p 3000:80 \
  #           ghcr.io/towech-financeapp/webclient:latest
  #           docker image prune -f
